### ISSUE TITLE
Rename the module

### ISSUE THREAD

**Issue by adam-lynch** [mllrsohn/nw-builder#161]
I guess we should rename this module to `nw-builder` when the first version of nwjs comes out (i.e. the first version of node-webkit with the new name).

**Comment by stevenvachon** [comment]
+1

**Comment by trevorah** [comment]
We should probably do this as part of a 2.0.0 release to avoid confusion. We can also [deprecate the module in npm](https://docs.npmjs.com/cli/deprecate) to make people aware of the name change.

**Comment by adam-lynch** [comment]
Ok, I'm going to do this. cc @steffenmllr

**Comment by adam-lynch** [comment]
@steffenmllr I need you to rename the repo to `nw-builder` and in the tagline/subject on the top of the main repo page, change `node-webkit` to `NW.js`. Thanks.

**Comment by adam-lynch** [comment]
npm module (nw-builder@2.0.0) published. Which usernames do I need to add as owners to the npm module?

**Comment by adam-lynch** [comment]
Grunt plugin updated. Same goes for that; rename the repo please @steffenmllr :+1:

**Comment by steffenmllr** [comment]
renamed the repo

**Comment by adam-lynch** [comment]
Thanks @steffenmllr, don't forget https://github.com/mllrsohn/grunt-node-webkit-builder :)

**Comment by steffenmllr** [comment]
done. we could also move the two repos into a new org where everybody has rename + access rights. what do you think ?

**Comment by adam-lynch** [comment]
@steffenmllr That would be great

**Comment by steffenmllr** [comment]
If you come up with a name, i'll transfer the repos

**Comment by adam-lynch** [comment]
@steffenmllr I've spoken to Roger Wang, could you transfer them to the https://github.com/nwjs organization? :grinning:!

**Comment by steffenmllr** [comment]
It seem like I need admin rights for nwjs to transfer the repo, @adam-lynch do you have any contact info from Roger ?

**Comment by adam-lynch** [comment]
@steffenmllr I'm a member of the nw.js org now. That's not good enough though is it?

**Comment by adam-lynch** [comment]
Wait, isn't it just this form? 
<img width="475" alt="screen shot 2015-07-17 at 13 08 32" src="https://cloud.githubusercontent.com/assets/1427241/8746813/04a67f6a-2c85-11e5-8039-c6176b1c79d6.png">

Once you do that, Roger has to accept I assume and then it's done

**Comment by steffenmllr** [comment]
I've given you admin rights to the two repos so you should be able to transfer the repos.
We should create a blank repo with a hint that the repo moved for google and deep links

**Comment by adam-lynch** [comment]
<img width="995" alt="screen shot 2015-07-17 at 13 12 26" src="https://cloud.githubusercontent.com/assets/1427241/8746858/82cf20a4-2c85-11e5-91c3-4be3e5231a4f.png">

Weird. I'll sort it out with Roger.

---

>I've given you admin rights to the two repos so you should be able to transfer the repos.
We should create a blank repo with a hint that the repo moved for google and deep links
 
I think GitHub redirects you anyway? I guess we can see when we do it

**Comment by adam-lynch** [comment]
I assumed I could give Roger admin access to these repos. Could you do it @steffenmllr? His username is @rogerwang

**Comment by steffenmllr** [comment]
done

**Comment by adam-lynch** [comment]
Done.

Now, who should have access?
