### ISSUE TITLE
Unable to download nodewebkit when running from behind corporate firewall.

### ISSUE THREAD

**Issue by yuchuan1** [mllrsohn/nw-builder#212]
I put my scripts on a Jenkins server behind the firewall which requires a user name and a password for the proxy.

When I run the program, it would not download the binary and gave me this error. 
"Unable to download nodewebkit."

Is there any place that I can set the proxy for node-webkit-builder?

**Comment by purtuga** [comment]
I was having the same problem and fixed the issue by ensuring that the following environment variable are exported in the executing environment:

```
HTTP_PROXY (or http_proxy)
HTTPS_PROXY (or https_proxy)
NO_PROXY  (or no_proxy)
```
I found this by looking at the [change](https://github.com/mllrsohn/node-webkit-builder/commit/94278fd7bea089879322d4b01a012dc5a6827929) `node-webkit-builder` made to support proxies... which basically defers to using `request` ([link](https://www.npmjs.com/package/request#proxies)) module...

**Comment by adam-lynch** [comment]
@yuchuan1 does that work for you?

**Comment by purtuga** [comment]
Yes, still working to this day.

**Comment by yuchuan1** [comment]
Nope, it still doesn't work for me.
My Jenkins is on a windows server, after setting HTTP_PROXY and HTTPS_PROXY, I still got "Unable to download nodewebkit." error

**Comment by yuchuan1** [comment]
I finally resolved the issue by installing a CNTLM according to this [stackoverflow post](http://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy).

**Comment by juri33** [comment]
i have the same issue:

with "version: "latest"
Error: Received status code 403 when checking for available versions.

or 
Error: Unable to download nodewebkit.

generally npm is working.

**Comment by adam-lynch** [comment]
@juri33 there's a bug with latest. It's getting an alpha build incorrectly. Please specify a version (0.12.3 is the latest valid one).

**Comment by juri33** [comment]
hmmm, changed to
 version: "0.12.3"

=> Error: Unable to download nodewebkit.

**Comment by adam-lynch** [comment]
@juri33 Now that's weird. Can you make sure to delete the cache directory? Could you share the code you have for calling `nw-builder` maybe too?

**Comment by juri33** [comment]
@adam-lynch thx

deleting the cache doesn't change something. Here is my gulp task:

gulp.task("build:nw", function (callback) {
  var nw = new NwBuilder({
    files: "app/**/*",
    version: "0.12.3",
    platforms: ["win64"],
    cacheDir: "c:\\tools\\nwjs\\" + "/.nwjs-cache",
    buildDir: "./build"
  });

  nw.build()
    .then(function () {
      callback();
    }).catch(function (error) {
      callback(error);
    });
});

**Comment by adam-lynch** [comment]
@juri33 hmmm that all looks fine. I'm not sure what's up to be honest.
